---
title: Binaire held
hero_image: images/banner.png
description: Scoor punten door de noten van een nummer te spelen terwijl ze voorbij
  scrollen
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-02
steps:
- title: Inleiding
- title: Toetsaanslagen
- title: Binaire getallen
  completion:
  - engaged
- title: Speel noten
- title: Scrollende noten
- title: Bewaar je liedje
- title: Meer aangepaste blokken
- title: Houd een score bij
  completion:
  - internal
- title: 'Uitdaging: ga verder'
  challenge: true