title: Binary Hero
hero_image: images/banner.png
description: Score points by playing the notes of a song as they scroll down the Stage
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-02
steps: 
- title: Introduction
- title: Key presses
- title: Binary notes
- title: Playing notes
- title: Scrolling notes
- title: Storing songs
- title: More custom blocks
- title: Keeping score
- title: "Challenge: taking it further"
  challenge: true
- title: "What next?"