---
title: बाइनरी हीरो
hero_image: images/banner.png
description: जैसे ही वे स्क्रॉल करके निकलते हैं, किसी गाने के स्वर चलाकर अंक प्राप्त
  करें
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-02
steps:
- title: परिचय
- title: कुंजी दबाना
- title: बाइनरी संख्याएँ
  completion:
  - engaged
- title: स्वर बजाना
- title: स्वरों को स्क्रॉल करना
- title: अपना गाना संगृहीत करें
- title: अधिक कस्टम ब्लॉक्स
- title: सस्कोर रखिए
  completion:
  - internal
- title: 'चुनौती: इसे आगे बढ़ाएँ'
  challenge: true