---
title: Binary hero
hero_image: imagens/banner.png
description: Score points by playing the notes of a song as they scroll past
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-02-01
steps:
  - 
    title: Introdução
  - 
    title: Key presses
  - 
    title: Binary notes
  - 
    title: Play notes
  - 
    title: Scrolling notes
  - 
    title: Store your song
  - 
    title: More custom blocks
  - 
    title: Keep a score
  - 
    title: "Challenge: take it further"
    challenge: true
  - 
    title: "E agora?"
