---
title: Binary hero
hero_image: images/banner.png
description: Gana puntos al tocar las notas de la canción que van pasando
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-02
steps:
  - 
    title: Introducción
  - 
    title: Presionar teclas
  - 
    title: Notas binarias
  - 
    title: Reproducir notas
  - 
    title: Scrolling notes
  - 
    title: Guarda tu canción
  - 
    title: Más bloques personalizados
  - 
    title: Keep a score
  - 
    title: "Desafío: ve más allá"
    challenge: true
  - 
    title: "¿Qué sigue?"
