---
title: Bohater binarny
hero_image: images/banner.png
description: Zdobywaj punkty, odtwarzając nuty przewijanego utworu
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-02
steps:
  - 
    title: Wprowadzenie correct
  - 
    title: Key presses
  - 
    title: Binary notes
  - 
    title: Play notes
  - 
    title: Scrolling notes
  - 
    title: Store your song
  - 
    title: More custom blocks
  - 
    title: Keep a score
  - 
    title: "Challenge: take it further"
    challenge: true
  - 
    title: "What next?"
