---
title: Virtuose du binaire
hero_image: images/banner.png
description: Marquer des points en jouant les notes d'une chanson quand elles défilent
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-11-02
steps:
  - 
    title: Introduction
  - 
    title: Touches pressées
  - 
    title: Notes binaires
  - 
    title: Jouer des notes
  - 
    title: Notes qui défilent
  - 
    title: Stocker ta chanson
  - 
    title: Plus de blocs personnalisés
  - 
    title: Garder un score
  - 
    title: "Défi : Aller plus loin"
    challenge: true
  - 
    title: "Et ensuite ?"
